/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author RAHAN
 */
public class updateframe extends javax.swing.JFrame {

    /**
     * Creates new form updateframe
     */
    public updateframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dept1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        dob1 = new javax.swing.JTextField();
        gen1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        status1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        design1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        add1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        sal1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        exp1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qua1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        empid1 = new javax.swing.JTextField();
        update1 = new javax.swing.JButton();
        search1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept1ActionPerformed(evt);
            }
        });
        getContentPane().add(dept1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 178, 30));

        jLabel6.setText("Email Id");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 193, 70, -1));

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 65, 190, -1));
        getContentPane().add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 190, -1));
        getContentPane().add(gen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 155, 190, -1));

        jLabel14.setText("Status");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 76, -1));
        getContentPane().add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 195, 190, -1));
        getContentPane().add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 180, 30));

        jLabel7.setText("Desgination");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 235, 80, -1));

        design1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                design1ActionPerformed(evt);
            }
        });
        getContentPane().add(design1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 235, 190, -1));

        jLabel8.setText("Mobile Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 285, 98, -1));

        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 280, 190, -1));

        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 76, -1));

        add1.setColumns(20);
        add1.setRows(5);
        jScrollPane1.setViewportView(add1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 325, 190, 69));

        jLabel10.setText("Salary");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 76, -1));

        sal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sal1ActionPerformed(evt);
            }
        });
        getContentPane().add(sal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 178, -1));

        jLabel11.setText("Experience");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 76, -1));
        getContentPane().add(exp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 176, 30));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 68, 70, -1));

        jLabel12.setText("Qualification");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 76, -1));

        jLabel3.setText("DOB");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, -1));

        qua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qua1ActionPerformed(evt);
            }
        });
        getContentPane().add(qua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 178, -1));

        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 158, 70, -1));

        jLabel13.setText("Department");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 76, -1));

        jLabel1.setText("Employee ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(empid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 20, 190, -1));

        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        getContentPane().add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        search1.setText("Search");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        getContentPane().add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void design1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_design1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_design1ActionPerformed

    private void sal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sal1ActionPerformed

    private void qua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qua1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
      String var = empid1.getText().trim();
      String var2 = name1.getText();
      String var3 = dob1.getText();
      String var4 = gen1.getText();
      String var5 = email1.getText();
      String var6 = design1.getText();
      String var7 = num1.getText();
      String var8= add1.getText();
      String var9= dept1.getText();
      String var10 = qua1.getText();
      String var11 = sal1.getText();
      String var12 = exp1.getText();
      String var13 = status1.getText();
      
      
        if(empid1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Search key not Found !");
        } 
        else {
                try {
                       Connection con  = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\SHAIK NAQUIBUDDIN\\Documents\\database.accdb");
                       ResultSet rs;
                       Statement st = con.createStatement();
                       String sql = "update mytable set Name='"+var2+"' , DOB='"+var3+"' , Gender='"+var4+"' ,Email='"+var5+"' , Designation='"+var6+"' , MobileNumber='"+var7+"' ,Address='"+var8+"' , Department='"+var9+"' , Qualification='"+var10+"' ,Salary='"+var11+"' , Experience='"+var12+"' , Status='"+var13+"' where Employeeid='"+var+"'";
                       st.executeUpdate(sql);
                       JOptionPane.showMessageDialog(null,"Update Complete");
                    }
                catch(Exception e)
                   {
                      System.out.println(e.getMessage());
                    }
           }       
        
        
        
        
        
    }//GEN-LAST:event_update1ActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        String var = empid1.getText();
        try {
            Connection con  = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\SHAIK NAQUIBUDDIN\\Documents\\database.accdb");
            Statement st = con.createStatement();
            ResultSet rs;
            String sqlQuery = "select * from mytable where Employeeid='"+var+"'";
            rs  = st.executeQuery(sqlQuery);
            while(rs.next())
            {
                String name = rs.getString("Name");
                name1.setText(name);
                
                String dob = rs.getString("DOB");
                dob1.setText(dob);
                
                String gen = rs.getString("Gender");
                gen1.setText(gen);
                
                String email = rs.getString("Email");
                email1.setText(email);
                
                String design = rs.getString("Designation");
                design1.setText(design);
                
                String num = rs.getString("MobileNumber");
                num1.setText(num);
                
                String add = rs.getString("Address");
                add1.setText(add);
                
                String dept = rs.getString("Department");
                dept1.setText(dept);
                
                String qua = rs.getString("Qualification");
                qua1.setText(qua);
                
                String sal = rs.getString("Salary");
                sal1.setText(sal);
                       
                String exp = rs.getString("Experience");
                exp1.setText(exp);
                
                String status = rs.getString("Status");
                status1.setText(status); 
            }
        }catch(Exception e) {
            System.out.println(e.getMessage());
        }
    
    }//GEN-LAST:event_search1ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void dept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dept1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dept1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        setVisible(false);
        mainmenu m = new mainmenu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add1;
    private javax.swing.JTextField dept1;
    private javax.swing.JTextField design1;
    private javax.swing.JTextField dob1;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField empid1;
    private javax.swing.JTextField exp1;
    private javax.swing.JTextField gen1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField qua1;
    private javax.swing.JTextField sal1;
    private javax.swing.JButton search1;
    private javax.swing.JTextField status1;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
